### This workflow doesn't have access to secrets and has a read-only token
name: Dependabot PR Check
on:
  branches:
    - dependabot/*
jobs:
  check_dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - run: echo "PR created by Dependabot"