name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  workflow_run:
    workflows: ["Dependabot PR Check"]
    types: 
      - completed
  push:
    branches-ignore:
      - main
      - feat/production
      - dependabot/*
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    environment: 'Preview'
    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        run: npm install
      - name: Test
        run: npm run test
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}